const ActionTypes = {
    CURRENTUSER: 'CURRENTUSER',
    CURRENTUSERUID: 'CURRENTUSERUID',
    EVENTS: 'EVENTS',
    EVENTKEY: 'EVENTKEY',
    GOINGKEY: 'GOINGKEY',
    NOTGOINGKEY: 'NOTGOINGKEY',
    CHANGES: 'CHANGES'
}

export default ActionTypes;